import {
	UseColumnOrderInstanceProps,
	UseColumnOrderState,
	UseExpandedHooks,
	UseExpandedInstanceProps,
	UseExpandedOptions,
	UseExpandedRowProps,
	UseExpandedState,
	UseFiltersColumnOptions,
	UseFiltersColumnProps,
	UseFiltersInstanceProps,
	UseFiltersOptions,
	UseFiltersState,
	UseGlobalFiltersColumnOptions,
	UseGlobalFiltersInstanceProps,
	UseGlobalFiltersOptions,
	UseGlobalFiltersState,
	UseGroupByCellProps,
	UseGroupByColumnOptions,
	UseGroupByColumnProps,
	UseGroupByHooks,
	UseGroupByInstanceProps,
	UseGroupByOptions,
	UseGroupByRowProps,
	UseGroupByState,
	UsePaginationInstanceProps,
	UsePaginationOptions,
	UsePaginationState,
	UseResizeColumnsColumnOptions,
	UseResizeColumnsColumnProps,
	UseResizeColumnsOptions,
	UseResizeColumnsState,
	UseRowSelectHooks,
	UseRowSelectInstanceProps,
	UseRowSelectOptions,
	UseRowSelectRowProps,
	UseRowSelectState,
	UseRowStateCellProps,
	UseRowStateInstanceProps,
	UseRowStateOptions,
	UseRowStateRowProps,
	UseRowStateState,
	UseSortByColumnOptions,
	UseSortByColumnProps,
	UseSortByHooks,
	UseSortByInstanceProps,
	UseSortByOptions,
	UseSortByState
} from 'react-table';
  
  declare module 'react-table' {
    // take this file as-is, or comment out the sections that don't apply to your plugin configuration
  
    export interface HeaderGroup<D extends object>
    extends UsePaginationOptions<D>,
      UseSortByOptions<D> {}}